# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'Firebase', '>= 2.5.0'

target 'Lift' do

end

target 'LiftTests' do

end

target 'LiftUITests' do

end

